FROM oven/bun:latest

ENV RUNNING_IN_DOCKER=true

WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN bun install

EXPOSE 4991 5173 40000

# Run both Vite dev server and Bun server
CMD ["sh", "-c", "cd apps/client && bun run dev --host 0.0.0.0 & cd apps/server && bun run dev"]
