name: Build Sharkord
description: Install Bun dependencies and build server artifacts. Requires checkout before use.

inputs:
  bun_version:
    description: Bun version to install
    required: false
    default: 1.3.5
  bump:
    description: Version bump mode (none, patch, minor, major)
    required: false
    default: none

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun_version }}

    - name: Install dependencies
      shell: bash
      run: bun install

    - name: Build app
      shell: bash
      run: |
        cd apps/server
        bun run build --bump "${{ inputs.bump }}"
