name: Docker Build And Publish
description: Set up Docker build tooling, authenticate, and build/push multi-arch images.

inputs:
  docker_username:
    description: Docker Hub username
    required: true
  docker_password:
    description: Docker Hub password or token
    required: true
  tags:
    description: Docker image tags (newline separated)
    required: true
  labels:
    description: Docker image labels (newline separated)
    required: false
    default: ""
  context:
    description: Docker build context path
    required: false
    default: "."
  platforms:
    description: Target platforms
    required: false
    default: linux/amd64,linux/arm64
  qemu_platforms:
    description: Platforms to register with QEMU
    required: false
    default: arm64

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.qemu_platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
